// SPDX-FileCopyrightText: 2025-2026 RAprogramm <andrey.rozanov.vl@gmail.com>
// SPDX-License-Identifier: MIT

//! CRUD handler generation with utoipa annotations.
//!
//! Generates REST handlers for CRUD operations on entities.
//! Each handler includes `#[utoipa::path]` annotations for OpenAPI
//! documentation.
//!
//! # Generated Handlers
//!
//! | Operation | HTTP Method | Path Pattern | Handler |
//! |-----------|-------------|--------------|---------|
//! | Create | POST | `/{prefix}/{entities}` | `create_{entity}` |
//! | Get | GET | `/{prefix}/{entities}/{id}` | `get_{entity}` |
//! | Update | PATCH | `/{prefix}/{entities}/{id}` | `update_{entity}` |
//! | Delete | DELETE | `/{prefix}/{entities}/{id}` | `delete_{entity}` |
//! | List | GET | `/{prefix}/{entities}` | `list_{entity}` |
//!
//! # Example
//!
//! For `User` entity with `api(tag = "Users", handlers)`:
//!
//! ```rust,ignore
//! #[utoipa::path(
//!     post,
//!     path = "/api/v1/users",
//!     tag = "Users",
//!     request_body = CreateUserRequest,
//!     responses(
//!         (status = 201, body = UserResponse),
//!         (status = 400, description = "Validation error"),
//!         (status = 500, description = "Internal server error")
//!     )
//! )]
//! pub async fn create_user(
//!     State(pool): State<Arc<PgPool>>,
//!     Json(dto): Json<CreateUserRequest>,
//! ) -> Result<(StatusCode, Json<UserResponse>), StatusCode> {
//!     let entity = pool.create(dto).await.map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
//!     Ok((StatusCode::CREATED, Json(UserResponse::from(entity))))
//! }
//! ```

use convert_case::{Case, Casing};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::entity::parse::EntityDef;

/// Generate all CRUD handler functions for the entity.
pub fn generate(entity: &EntityDef) -> TokenStream {
    if !entity.api_config().has_handlers() {
        return TokenStream::new();
    }

    let create = generate_create_handler(entity);
    let get = generate_get_handler(entity);
    let update = generate_update_handler(entity);
    let delete = generate_delete_handler(entity);
    let list = generate_list_handler(entity);

    quote! {
        #create
        #get
        #update
        #delete
        #list
    }
}

/// Generate the create handler.
fn generate_create_handler(entity: &EntityDef) -> TokenStream {
    let vis = &entity.vis;
    let entity_name = entity.name();
    let api_config = entity.api_config();

    let handler_name = format_ident!("create_{}", entity.name_str().to_case(Case::Snake));
    let create_dto = entity.ident_with("Create", "Request");
    let response_dto = entity.ident_with("", "Response");

    let path = build_collection_path(entity);
    let tag = api_config.tag_or_default(&entity.name_str());

    let security_attr = build_security_attr(entity, "create");
    let deprecated_attr = build_deprecated_attr(entity);

    let utoipa_attr = if security_attr.is_empty() {
        quote! {
            #[utoipa::path(
                post,
                path = #path,
                tag = #tag,
                request_body = #create_dto,
                responses(
                    (status = 201, body = #response_dto, description = "Created"),
                    (status = 400, description = "Validation error"),
                    (status = 500, description = "Internal server error")
                )
                #deprecated_attr
            )]
        }
    } else {
        quote! {
            #[utoipa::path(
                post,
                path = #path,
                tag = #tag,
                request_body = #create_dto,
                responses(
                    (status = 201, body = #response_dto, description = "Created"),
                    (status = 400, description = "Validation error"),
                    (status = 401, description = "Unauthorized"),
                    (status = 500, description = "Internal server error")
                ),
                #security_attr
                #deprecated_attr
            )]
        }
    };

    let doc = format!(
        "Create a new {} entity.\n\n\
         Generated by entity-derive.",
        entity_name
    );

    quote! {
        #[doc = #doc]
        #utoipa_attr
        #vis async fn #handler_name<R>(
            axum::extract::State(repo): axum::extract::State<std::sync::Arc<R>>,
            axum::extract::Json(dto): axum::extract::Json<#create_dto>,
        ) -> Result<(axum::http::StatusCode, axum::response::Json<#response_dto>), axum::http::StatusCode>
        where
            R: #entity_name Repository + 'static,
        {
            let entity = repo.create(dto).await.map_err(|_| axum::http::StatusCode::INTERNAL_SERVER_ERROR)?;
            Ok((axum::http::StatusCode::CREATED, axum::response::Json(#response_dto::from(entity))))
        }
    }
}

/// Generate the get handler.
fn generate_get_handler(entity: &EntityDef) -> TokenStream {
    let vis = &entity.vis;
    let entity_name = entity.name();
    let api_config = entity.api_config();
    let id_field = entity.id_field();
    let id_type = &id_field.ty;

    let handler_name = format_ident!("get_{}", entity.name_str().to_case(Case::Snake));
    let response_dto = entity.ident_with("", "Response");

    let path = build_item_path(entity);
    let tag = api_config.tag_or_default(&entity.name_str());

    let security_attr = build_security_attr(entity, "get");
    let deprecated_attr = build_deprecated_attr(entity);

    let utoipa_attr = if security_attr.is_empty() {
        quote! {
            #[utoipa::path(
                get,
                path = #path,
                tag = #tag,
                params(("id" = #id_type, Path, description = "Entity ID")),
                responses(
                    (status = 200, body = #response_dto, description = "Found"),
                    (status = 404, description = "Not found"),
                    (status = 500, description = "Internal server error")
                )
                #deprecated_attr
            )]
        }
    } else {
        quote! {
            #[utoipa::path(
                get,
                path = #path,
                tag = #tag,
                params(("id" = #id_type, Path, description = "Entity ID")),
                responses(
                    (status = 200, body = #response_dto, description = "Found"),
                    (status = 401, description = "Unauthorized"),
                    (status = 404, description = "Not found"),
                    (status = 500, description = "Internal server error")
                ),
                #security_attr
                #deprecated_attr
            )]
        }
    };

    let doc = format!(
        "Get {} entity by ID.\n\n\
         Generated by entity-derive.",
        entity_name
    );

    quote! {
        #[doc = #doc]
        #utoipa_attr
        #vis async fn #handler_name<R>(
            axum::extract::State(repo): axum::extract::State<std::sync::Arc<R>>,
            axum::extract::Path(id): axum::extract::Path<#id_type>,
        ) -> Result<axum::response::Json<#response_dto>, axum::http::StatusCode>
        where
            R: #entity_name Repository + 'static,
        {
            let entity = repo
                .find_by_id(id)
                .await
                .map_err(|_| axum::http::StatusCode::INTERNAL_SERVER_ERROR)?
                .ok_or(axum::http::StatusCode::NOT_FOUND)?;
            Ok(axum::response::Json(#response_dto::from(entity)))
        }
    }
}

/// Generate the update handler.
fn generate_update_handler(entity: &EntityDef) -> TokenStream {
    let vis = &entity.vis;
    let entity_name = entity.name();
    let api_config = entity.api_config();
    let id_field = entity.id_field();
    let id_type = &id_field.ty;

    let handler_name = format_ident!("update_{}", entity.name_str().to_case(Case::Snake));
    let update_dto = entity.ident_with("Update", "Request");
    let response_dto = entity.ident_with("", "Response");

    let path = build_item_path(entity);
    let tag = api_config.tag_or_default(&entity.name_str());

    let security_attr = build_security_attr(entity, "update");
    let deprecated_attr = build_deprecated_attr(entity);

    let utoipa_attr = if security_attr.is_empty() {
        quote! {
            #[utoipa::path(
                patch,
                path = #path,
                tag = #tag,
                params(("id" = #id_type, Path, description = "Entity ID")),
                request_body = #update_dto,
                responses(
                    (status = 200, body = #response_dto, description = "Updated"),
                    (status = 400, description = "Validation error"),
                    (status = 404, description = "Not found"),
                    (status = 500, description = "Internal server error")
                )
                #deprecated_attr
            )]
        }
    } else {
        quote! {
            #[utoipa::path(
                patch,
                path = #path,
                tag = #tag,
                params(("id" = #id_type, Path, description = "Entity ID")),
                request_body = #update_dto,
                responses(
                    (status = 200, body = #response_dto, description = "Updated"),
                    (status = 400, description = "Validation error"),
                    (status = 401, description = "Unauthorized"),
                    (status = 404, description = "Not found"),
                    (status = 500, description = "Internal server error")
                ),
                #security_attr
                #deprecated_attr
            )]
        }
    };

    let doc = format!(
        "Update {} entity by ID.\n\n\
         Generated by entity-derive.",
        entity_name
    );

    quote! {
        #[doc = #doc]
        #utoipa_attr
        #vis async fn #handler_name<R>(
            axum::extract::State(repo): axum::extract::State<std::sync::Arc<R>>,
            axum::extract::Path(id): axum::extract::Path<#id_type>,
            axum::extract::Json(dto): axum::extract::Json<#update_dto>,
        ) -> Result<axum::response::Json<#response_dto>, axum::http::StatusCode>
        where
            R: #entity_name Repository + 'static,
        {
            let entity = repo
                .update(id, dto)
                .await
                .map_err(|_| axum::http::StatusCode::INTERNAL_SERVER_ERROR)?;
            Ok(axum::response::Json(#response_dto::from(entity)))
        }
    }
}

/// Generate the delete handler.
fn generate_delete_handler(entity: &EntityDef) -> TokenStream {
    let vis = &entity.vis;
    let entity_name = entity.name();
    let api_config = entity.api_config();
    let id_field = entity.id_field();
    let id_type = &id_field.ty;

    let handler_name = format_ident!("delete_{}", entity.name_str().to_case(Case::Snake));

    let path = build_item_path(entity);
    let tag = api_config.tag_or_default(&entity.name_str());

    let security_attr = build_security_attr(entity, "delete");
    let deprecated_attr = build_deprecated_attr(entity);

    let utoipa_attr = if security_attr.is_empty() {
        quote! {
            #[utoipa::path(
                delete,
                path = #path,
                tag = #tag,
                params(("id" = #id_type, Path, description = "Entity ID")),
                responses(
                    (status = 204, description = "Deleted"),
                    (status = 404, description = "Not found"),
                    (status = 500, description = "Internal server error")
                )
                #deprecated_attr
            )]
        }
    } else {
        quote! {
            #[utoipa::path(
                delete,
                path = #path,
                tag = #tag,
                params(("id" = #id_type, Path, description = "Entity ID")),
                responses(
                    (status = 204, description = "Deleted"),
                    (status = 401, description = "Unauthorized"),
                    (status = 404, description = "Not found"),
                    (status = 500, description = "Internal server error")
                ),
                #security_attr
                #deprecated_attr
            )]
        }
    };

    let doc = format!(
        "Delete {} entity by ID.\n\n\
         Generated by entity-derive.",
        entity_name
    );

    quote! {
        #[doc = #doc]
        #utoipa_attr
        #vis async fn #handler_name<R>(
            axum::extract::State(repo): axum::extract::State<std::sync::Arc<R>>,
            axum::extract::Path(id): axum::extract::Path<#id_type>,
        ) -> Result<axum::http::StatusCode, axum::http::StatusCode>
        where
            R: #entity_name Repository + 'static,
        {
            let deleted = repo
                .delete(id)
                .await
                .map_err(|_| axum::http::StatusCode::INTERNAL_SERVER_ERROR)?;
            if deleted {
                Ok(axum::http::StatusCode::NO_CONTENT)
            } else {
                Err(axum::http::StatusCode::NOT_FOUND)
            }
        }
    }
}

/// Generate the list handler.
fn generate_list_handler(entity: &EntityDef) -> TokenStream {
    let vis = &entity.vis;
    let entity_name = entity.name();
    let api_config = entity.api_config();

    let handler_name = format_ident!("list_{}", entity.name_str().to_case(Case::Snake));
    let response_dto = entity.ident_with("", "Response");

    let path = build_collection_path(entity);
    let tag = api_config.tag_or_default(&entity.name_str());

    let security_attr = build_security_attr(entity, "list");
    let deprecated_attr = build_deprecated_attr(entity);

    let utoipa_attr = if security_attr.is_empty() {
        quote! {
            #[utoipa::path(
                get,
                path = #path,
                tag = #tag,
                params(
                    ("limit" = Option<i64>, Query, description = "Max items to return"),
                    ("offset" = Option<i64>, Query, description = "Items to skip")
                ),
                responses(
                    (status = 200, body = Vec<#response_dto>, description = "List of entities"),
                    (status = 500, description = "Internal server error")
                )
                #deprecated_attr
            )]
        }
    } else {
        quote! {
            #[utoipa::path(
                get,
                path = #path,
                tag = #tag,
                params(
                    ("limit" = Option<i64>, Query, description = "Max items to return"),
                    ("offset" = Option<i64>, Query, description = "Items to skip")
                ),
                responses(
                    (status = 200, body = Vec<#response_dto>, description = "List of entities"),
                    (status = 401, description = "Unauthorized"),
                    (status = 500, description = "Internal server error")
                ),
                #security_attr
                #deprecated_attr
            )]
        }
    };

    let doc = format!(
        "List {} entities with pagination.\n\n\
         Generated by entity-derive.",
        entity_name
    );

    quote! {
        /// Pagination query parameters.
        #[derive(Debug, Clone, serde::Deserialize)]
        #vis struct PaginationQuery {
            /// Maximum number of items to return.
            #[serde(default = "default_limit")]
            pub limit: i64,
            /// Number of items to skip.
            #[serde(default)]
            pub offset: i64,
        }

        fn default_limit() -> i64 { 100 }

        #[doc = #doc]
        #utoipa_attr
        #vis async fn #handler_name<R>(
            axum::extract::State(repo): axum::extract::State<std::sync::Arc<R>>,
            axum::extract::Query(pagination): axum::extract::Query<PaginationQuery>,
        ) -> Result<axum::response::Json<Vec<#response_dto>>, axum::http::StatusCode>
        where
            R: #entity_name Repository + 'static,
        {
            let entities = repo
                .list(pagination.limit, pagination.offset)
                .await
                .map_err(|_| axum::http::StatusCode::INTERNAL_SERVER_ERROR)?;
            let responses: Vec<#response_dto> = entities.into_iter().map(#response_dto::from).collect();
            Ok(axum::response::Json(responses))
        }
    }
}

/// Build the collection path (e.g., `/api/v1/users`).
fn build_collection_path(entity: &EntityDef) -> String {
    let api_config = entity.api_config();
    let prefix = api_config.full_path_prefix();
    let entity_path = entity.name_str().to_case(Case::Kebab);

    let path = format!("{}/{}s", prefix, entity_path);
    path.replace("//", "/")
}

/// Build the item path (e.g., `/api/v1/users/{id}`).
fn build_item_path(entity: &EntityDef) -> String {
    let collection = build_collection_path(entity);
    format!("{}/{{id}}", collection)
}

/// Build security attribute for a handler.
fn build_security_attr(entity: &EntityDef, _operation: &str) -> TokenStream {
    let api_config = entity.api_config();

    if let Some(security) = &api_config.security {
        let security_name = match security.as_str() {
            "bearer" => "bearer_auth",
            "api_key" => "api_key",
            "admin" => "admin_auth",
            "oauth2" => "oauth2",
            _ => "bearer_auth"
        };
        quote! { security(#security_name = []) }
    } else {
        TokenStream::new()
    }
}

/// Build deprecated attribute if API is deprecated.
fn build_deprecated_attr(entity: &EntityDef) -> TokenStream {
    if entity.api_config().is_deprecated() {
        quote! { , deprecated = true }
    } else {
        TokenStream::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_test_entity() -> EntityDef {
        let input: syn::DeriveInput = syn::parse_quote! {
            #[entity(table = "users", api(tag = "Users", handlers))]
            pub struct User {
                #[id]
                pub id: uuid::Uuid,
                #[field(create, update, response)]
                pub name: String,
            }
        };
        EntityDef::from_derive_input(&input).unwrap()
    }

    #[test]
    fn collection_path_format() {
        let entity = create_test_entity();
        let path = build_collection_path(&entity);
        assert_eq!(path, "/users");
    }

    #[test]
    fn item_path_format() {
        let entity = create_test_entity();
        let path = build_item_path(&entity);
        assert_eq!(path, "/users/{id}");
    }

    #[test]
    fn generates_handlers_when_enabled() {
        let entity = create_test_entity();
        let tokens = generate(&entity);
        let output = tokens.to_string();
        assert!(output.contains("create_user"));
        assert!(output.contains("get_user"));
        assert!(output.contains("update_user"));
        assert!(output.contains("delete_user"));
        assert!(output.contains("list_user"));
    }

    #[test]
    fn no_handlers_when_disabled() {
        let input: syn::DeriveInput = syn::parse_quote! {
            #[entity(table = "users", api(tag = "Users"))]
            pub struct User {
                #[id]
                pub id: uuid::Uuid,
            }
        };
        let entity = EntityDef::from_derive_input(&input).unwrap();
        let tokens = generate(&entity);
        assert!(tokens.is_empty());
    }
}
